# Generated by Django 3.1 on 2020-09-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_pic',
        ),
    ]
