# Generated by Django 3.1 on 2020-09-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200904_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_pic',
            new_name='user',
        ),
    ]
