# Generated by Django 3.1 on 2020-09-04 09:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_auto_20200904_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfileImg',
        ),
    ]
