# Generated by Django 3.1 on 2020-09-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200904_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileimg',
            old_name='profile_img',
            new_name='picture',
        ),
    ]
