# Generated by Django 3.1 on 2020-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200904_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimg',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
