# Generated by Django 3.1 on 2020-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=5),
        ),
    ]
