# Generated by Django 3.1 on 2020-10-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200916_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpdf',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='uploadpdf',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zip_file'),
        ),
    ]
